branches:
  only:
    - buddy
    - /^\d+\.\d+\.\d+$/ # regex
    - travis1

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - doc-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
    - pip install --user codecov
    - wget -P ./Parse/lib/ https://parseonbuddy.blob.core.windows.net/ppns/ppns-android-1.0.jar
    - export TZ=Etc/UTC

#    - mvn validate

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport

after_success:
#  - ./gradlew coveralls
  - codecov
# - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    all_branches: true
    branch: buddy
    tags: true