branches:
  only:
    - buddy
    - /^\d+\.\d+\.\d+$/ # regex

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - doc-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport --info

after_success:
#  - ./gradlew coveralls
  - codecov
# - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: buddy
    tags: true
